/**
 * pendulum_realtime.ino
 * ---------------------
 * Real-time simple pendulum simulation generated by MechanicsDSL.
 * Reads angular position from an MPU6050 IMU over I2C and integrates
 * the Lagrangian equations of motion on-device.
 *
 * System specification (MechanicsDSL DSL):
 *   \system{pendulum}
 *   \parameter{m}{1.0}{kg}
 *   \parameter{l}{0.25}{m}
 *   \lagrangian{0.5*m*l^2*\dot{theta}^2 - m*g*l*(1 - cos(theta))}
 *   \target{arduino}
 *
 * Hardware:
 *   - Arduino Uno / Nano / Mega (tested on Uno R3)
 *   - MPU6050 IMU (I2C, SDA=A4, SCL=A5 on Uno)
 *   - Optional: serial plotter for real-time visualization
 *
 * Wiring:
 *   MPU6050 VCC -> 3.3V
 *   MPU6050 GND -> GND
 *   MPU6050 SDA -> A4
 *   MPU6050 SCL -> A5
 *
 * Serial output (115200 baud):
 *   t_ms,theta_sim_rad,theta_imu_rad,omega_sim_rad_s,energy_J
 *
 * Author: MechanicsDSL (github.com/MechanicsDSL)
 * License: MIT
 */

#include <Wire.h>

// ---------------------------------------------------------------------------
// Physical parameters (MechanicsDSL \parameter blocks)
// ---------------------------------------------------------------------------
const float M_MASS = 1.0f;    // kg
const float L_LEN  = 0.25f;   // m
const float G_GRAV = 9.81f;   // m/s^2

// ---------------------------------------------------------------------------
// Integrator state
// ---------------------------------------------------------------------------
static float theta = 0.30f;   // rad  (initial condition)
static float omega = 0.00f;   // rad/s
static float t_sim = 0.0f;    // s

// Fixed timestep for embedded integration (4 ms = 250 Hz)
const float DT = 0.004f;

// ---------------------------------------------------------------------------
// MPU6050 register definitions
// ---------------------------------------------------------------------------
const uint8_t MPU6050_ADDR       = 0x68;
const uint8_t MPU6050_PWR_MGMT_1 = 0x6B;
const uint8_t MPU6050_ACCEL_XOUT = 0x3B;

// ---------------------------------------------------------------------------
// MechanicsDSL-generated: equations of motion
// Euler-Lagrange applied to L = 0.5*m*l^2*omega^2 - m*g*l*(1-cos(theta))
// yields: d(omega)/dt = -(g/l)*sin(theta)
// ---------------------------------------------------------------------------
inline float eom_domega(float theta_val) {
  return -(G_GRAV / L_LEN) * sinf(theta_val);
}

// ---------------------------------------------------------------------------
// MechanicsDSL-generated: total energy (Noether conserved quantity)
// H = 0.5*m*l^2*omega^2 + m*g*l*(1 - cos(theta))
// ---------------------------------------------------------------------------
inline float total_energy(float theta_val, float omega_val) {
  float T = 0.5f * M_MASS * L_LEN * L_LEN * omega_val * omega_val;
  float V = M_MASS * G_GRAV * L_LEN * (1.0f - cosf(theta_val));
  return T + V;
}

// ---------------------------------------------------------------------------
// Runge-Kutta 4 integrator (fixed step DT)
// State: [theta, omega]
// ---------------------------------------------------------------------------
void rk4_step(float dt) {
  // k1
  float k1_theta = omega;
  float k1_omega = eom_domega(theta);

  // k2
  float th2 = theta + 0.5f * dt * k1_theta;
  float om2 = omega + 0.5f * dt * k1_omega;
  float k2_theta = om2;
  float k2_omega = eom_domega(th2);

  // k3
  float th3 = theta + 0.5f * dt * k2_theta;
  float om3 = omega + 0.5f * dt * k2_omega;
  float k3_theta = om3;
  float k3_omega = eom_domega(th3);

  // k4
  float th4 = theta + dt * k3_theta;
  float om4 = omega + dt * k3_omega;
  float k4_theta = om4;
  float k4_omega = eom_domega(th4);

  theta += (dt / 6.0f) * (k1_theta + 2*k2_theta + 2*k3_theta + k4_theta);
  omega += (dt / 6.0f) * (k1_omega + 2*k2_omega + 2*k3_omega + k4_omega);
  t_sim += dt;
}

// ---------------------------------------------------------------------------
// MPU6050 initialisation and angle reading
// ---------------------------------------------------------------------------
void mpu6050_init() {
  Wire.beginTransmission(MPU6050_ADDR);
  Wire.write(MPU6050_PWR_MGMT_1);
  Wire.write(0x00);  // Wake up
  Wire.endTransmission(true);
  delay(100);
}

float mpu6050_read_angle_rad() {
  Wire.beginTransmission(MPU6050_ADDR);
  Wire.write(MPU6050_ACCEL_XOUT);
  Wire.endTransmission(false);
  Wire.requestFrom(MPU6050_ADDR, (uint8_t)6, (uint8_t)true);

  int16_t ax = (Wire.read() << 8) | Wire.read();
  int16_t ay = (Wire.read() << 8) | Wire.read();
  int16_t az = (Wire.read() << 8) | Wire.read();

  // Convert raw accelerometer to g-force
  float ax_g = ax / 16384.0f;
  float az_g = az / 16384.0f;

  // Compute tilt angle from gravitational projection
  return atan2f(ax_g, az_g);
}

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------
void setup() {
  Serial.begin(115200);
  Wire.begin();
  mpu6050_init();

  // Print CSV header
  Serial.println(F("t_ms,theta_sim_rad,theta_imu_rad,omega_sim_rad_s,energy_J"));
}

// ---------------------------------------------------------------------------
// Main loop: integrate, read IMU, log at 250 Hz
// ---------------------------------------------------------------------------
void loop() {
  static uint32_t last_us = 0;
  uint32_t now_us = micros();

  if (now_us - last_us >= (uint32_t)(DT * 1e6)) {
    last_us = now_us;

    // Integrate one step
    rk4_step(DT);

    // Read IMU angle
    float theta_imu = mpu6050_read_angle_rad();

    // Compute conserved energy (MechanicsDSL Noether monitor)
    float E = total_energy(theta, omega);

    // Output CSV row
    Serial.print(millis());       Serial.print(',');
    Serial.print(theta, 6);       Serial.print(',');
    Serial.print(theta_imu, 6);   Serial.print(',');
    Serial.print(omega, 6);       Serial.print(',');
    Serial.println(E, 6);
  }
}
