/**
 * double_pendulum.ino
 * -------------------
 * Real-time double pendulum simulation generated by MechanicsDSL.
 * Integrates Lagrangian equations of motion at 200 Hz on Arduino Mega.
 * Outputs state via serial for real-time plotting.
 *
 * DSL specification:
 *   \system{double_pendulum}
 *   \parameter{m}{1.0}{kg}
 *   \parameter{l}{0.3}{m}
 *   \lagrangian{
 *       0.5*m*l^2*(2*\dot{theta1}^2 + \dot{theta2}^2
 *                  + 2*\dot{theta1}*\dot{theta2}*cos(theta1-theta2))
 *       + m*g*l*(2*cos(theta1) + cos(theta2))
 *   }
 *   \target{arduino}
 *
 * Hardware: Arduino Mega 2560 (recommended — double precision float ops)
 * Serial output (115200 baud): t_ms,theta1,theta2,omega1,omega2,energy
 *
 * Author: MechanicsDSL (github.com/MechanicsDSL)
 * License: MIT
 */

// Physical parameters
const float M_MASS = 1.0f;
const float L_LEN  = 0.3f;
const float G_GRAV = 9.81f;

// Integration
const float DT     = 0.005f;   // 200 Hz

// State
static float theta1 = 0.8f;
static float theta2 = 0.4f;
static float omega1 = 0.0f;
static float omega2 = 0.0f;
static float t_sim  = 0.0f;

// ---------------------------------------------------------------------------
// MechanicsDSL-generated: equations of motion
// ---------------------------------------------------------------------------
void eom(float th1, float th2, float w1, float w2,
         float& dth1, float& dth2, float& dw1, float& dw2) {
  const float delta  = th1 - th2;
  const float cos_d  = cosf(delta);
  const float sin_d  = sinf(delta);
  const float denom  = L_LEN * (2.0f - cos_d * cos_d);

  dth1 = w1;
  dth2 = w2;
  dw1  = ((-G_GRAV * 2.0f * sinf(th1))
          - sin_d * (w2*w2*L_LEN + w1*w1*L_LEN*cos_d)) / denom;
  dw2  = (sin_d * (2.0f*w1*w1*L_LEN
          + G_GRAV*cosf(th1) + w2*w2*L_LEN*cos_d)) / denom;
}

// ---------------------------------------------------------------------------
// MechanicsDSL-generated: Hamiltonian (Noether conserved energy)
// ---------------------------------------------------------------------------
float hamiltonian(float th1, float th2, float w1, float w2) {
  float T = 0.5f*M_MASS*L_LEN*L_LEN*(2*w1*w1 + w2*w2 + 2*w1*w2*cosf(th1-th2));
  float V = -M_MASS*G_GRAV*L_LEN*(2*cosf(th1) + cosf(th2));
  return T + V;
}

// ---------------------------------------------------------------------------
// RK4 integrator
// ---------------------------------------------------------------------------
void rk4_step(float dt) {
  float k1_th1, k1_th2, k1_w1, k1_w2;
  float k2_th1, k2_th2, k2_w1, k2_w2;
  float k3_th1, k3_th2, k3_w1, k3_w2;
  float k4_th1, k4_th2, k4_w1, k4_w2;

  eom(theta1,                  theta2,                  omega1,                  omega2,                  k1_th1, k1_th2, k1_w1, k1_w2);
  eom(theta1+0.5f*dt*k1_th1,  theta2+0.5f*dt*k1_th2,  omega1+0.5f*dt*k1_w1,  omega2+0.5f*dt*k1_w2,  k2_th1, k2_th2, k2_w1, k2_w2);
  eom(theta1+0.5f*dt*k2_th1,  theta2+0.5f*dt*k2_th2,  omega1+0.5f*dt*k2_w1,  omega2+0.5f*dt*k2_w2,  k3_th1, k3_th2, k3_w1, k3_w2);
  eom(theta1+dt*k3_th1,        theta2+dt*k3_th2,        omega1+dt*k3_w1,        omega2+dt*k3_w2,        k4_th1, k4_th2, k4_w1, k4_w2);

  theta1 += (dt/6.0f)*(k1_th1+2*k2_th1+2*k3_th1+k4_th1);
  theta2 += (dt/6.0f)*(k1_th2+2*k2_th2+2*k3_th2+k4_th2);
  omega1 += (dt/6.0f)*(k1_w1 +2*k2_w1 +2*k3_w1 +k4_w1);
  omega2 += (dt/6.0f)*(k1_w2 +2*k2_w2 +2*k3_w2 +k4_w2);
  t_sim  += dt;
}

void setup() {
  Serial.begin(115200);
  Serial.println(F("t_ms,theta1,theta2,omega1,omega2,energy"));
}

void loop() {
  static uint32_t last_us = 0;
  uint32_t now_us = micros();
  if (now_us - last_us >= (uint32_t)(DT * 1e6)) {
    last_us = now_us;
    rk4_step(DT);
    float E = hamiltonian(theta1, theta2, omega1, omega2);
    Serial.print(millis());   Serial.print(',');
    Serial.print(theta1, 5);  Serial.print(',');
    Serial.print(theta2, 5);  Serial.print(',');
    Serial.print(omega1, 5);  Serial.print(',');
    Serial.print(omega2, 5);  Serial.print(',');
    Serial.println(E, 5);
  }
}
